name: ecommerce_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  carousel_pro: ^1.0.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  google_sign_in: ^5.3.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  firebase_storage: ^10.2.16
  firebase_database: ^9.0.14
  provider: ^6.0.2
  uuid: ^3.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^11.4.0
  flutter_spinkit: ^5.1.0
  progress_dialog: ^1.2.4
  image_picker: ^0.8.5+3
  bubble_tab_indicator: ^0.1.4
  flutter_staggered_grid_view: ^0.6.1
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutterwave: ^1.0.1
  sizer: ^2.0.15
  email_validator: ^2.0.1
  http: ^0.13.3
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.1
  device_preview: ^1.0.0




flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icons/shoplaLogo.png"




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - images/carousel/
   - images/categories_icons/
   - images/cart/
   - images/loading_gif/
   - images/mobile_money/
   - images/
   - images/banners/
   - images/logos/
   - images/img_place_holder/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
   - family: Poppins
     fonts:
       - asset: google_fonts/Poppins-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
